baseURL = "https://github.com/philips413"
languageCode = "ko-kr"
title = ":::김도령의 우당탕탕 Lab실:::"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Philips413"
  description = "그러므로 너희의 담대함을 버리지 말라. 이것이 큰 상을 얻게 하느니라 -히 10:35"
  github = "philips413"
  email = "kimehfud1@naver.com"
  rss = false
  lastmod = false
  favicon = "/images/github.png"
  location = "Korea"
  avatar  = "/images/kermit.png"
#   [[params.links]]
#     title = "Link"
#     href = "https://github.com/philips413"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]